sotrh/learn-wgpu

- docs/beginner/tutorial2-swapchain/README.md
Fixes #5 
For some reason all my editors keep removing the newline at the end of the file. Sorry about that.
> Fix missing call to self.queue.submit

- docs/beginner/tutorial6-uniforms/README.md
> Fix static_tree instead of static-tree type

- code/beginner/tutorial1-window/src/main.rs
- docs/beginner/tutorial1-window/README.md
- docs/beginner/tutorial2-swapchain/README.md
@sotrh Thank you for the tutorials!  I went through the first two tutorials and tried to improve the wording I had trouble understand and the code that didn't seem to work.  I hope this is helpful. 😄 
This overlaps with the fix in #37 that I didn't see until I had made the same fix independently.
> Fixed some things I noticed while doing tutorial 1 and tutorial 2.

- docs/beginner/tutorial2-swapchain/README.md
Noticed this when following along with the tutorial.
The `resize` function is not asynchronous, and thus doesn't return a future that needs to be awaited.
-----
Also, thanks for creating this tutorial! I'm very new to graphics program so it's going to be interesting to see how far I can get 😅
> Remove block_on in calls to State#resize

- docs/beginner/tutorial3-pipeline/README.md
- docs/beginner/tutorial4-buffer/README.md
Thank you for making this tutorial! I was only able to get as far as I had the time for, but it definitely helped me. I made notes of some fixes as I was going through it, which I'm submitting now.
> Some small fixes.

- docs/beginner/tutorial4-buffer/README.md
I acknowledge that some of these are purely subjective, but the improper `'s` irks me, heh.
> grammar fixes

- docs/beginner/tutorial9-models/README.md
> Add a description about to_rgba()

- docs/beginner/tutorial3-pipeline/README.md
... you have no idea how much trouble this caused me
> Add an explanation of what entry_point means

- docs/beginner/tutorial1-window/README.md
> Clarify what the wgpu-rs's vulkan feature does on Mac OS and other platforms

- code/intermediate/tutorial11-normals/src/light.vert
See https://github.com/gfx-rs/wgpu-rs/issues/429#issuecomment-656330761
> Fix a mismatch in light VS versus FS varying of v_color

- docs/beginner/tutorial2-swapchain/README.md
Awesome tutorial! Thanks for your work.
I just got a bit confused at this point whether to add the `WindowEvent` matching code to the inner or outer `match event`, had to check the code in the repo to make sure. Maybe this makes it clearer for other noobs like me?
> Suggestion: Indent event loop code snippet in swapchain tutorial

- docs/showcase/gifs/README.md
> break our your -> break out your

- docs/beginner/tutorial3-pipeline/README.md
c.f. https://github.com/gfx-rs/wgpu-rs/pull/545
> Refer to shadow mapping

- docs/beginner/tutorial7-instancing/README.md
Thanks for writing this tutorial -- it's been a very helpful resource! I made some very minor edits -- feel free to reject any of them :)
> Minor copy editing of instancing docs.

- docs/beginner/tutorial4-buffer/README.md
I tripped over this one while following along with the tutorial. I added a little link to extension traits as I'm aware the audience of this tutorial may not be familiar with them.
Please feel free to rewrite/throw out any of my copy as you see fit.  😄 
Thanks again for this phenomenal tutorial!
> Add `use` statement for DeviceExt

- docs/beginner/tutorial9-models/README.md
Changed from ```<...>/tutorial9-models/src/res/cube.zip``` to ```<...>/tutorial9-models/res/cube.zip```. 
(I hope i'm doing it right making such a micro pull requests >.>)
> Fixed the link to zip file

- docs/beginner/tutorial2-swapchain/README.md
- docs/beginner/tutorial5-textures/README.md
learn-wgpu is such a wonderful ressource for beginners, thank you !
> Minor changes

- docs/beginner/tutorial5-textures/README.md
https://docs.rs/wgpu/0.6.0/wgpu/util/struct.BufferInitDescriptor.html
> Texture: BufferInitDescriptor fields.

- docs/beginner/tutorial4-buffer/README.md
Not a big one, just being explicit where the fields need to be updated on the struct.
> Clarify changes to State struct

- run-all.sh
Hi @sotrh 
I noticed you had a TODO to run all tasks asynchronously. Using `&`*should*, on most platforms, accomplish this by backgrounding each task as it's spawned.
> Run all tasks asynchronously

- docs/beginner/tutorial9-models/README.md
Existing link wasn't pointing to normals page.
> Fix a broken link

- docs/beginner/tutorial4-buffer/README.md
> Fixed spelling mistake

- docs/beginner/tutorial2-swapchain/README.md
or add `winit::` here
``` rust
async fn new(window: &Window) -> Self {
```
> use winit::window::Window

- Cargo.lock
- code/beginner/tutorial9-models/Cargo.toml
- code/beginner/tutorial9-models/src/model.rs
- code/intermediate/tutorial10-lighting/Cargo.toml
- code/intermediate/tutorial10-lighting/src/model.rs
- code/intermediate/tutorial11-normals/Cargo.toml
- code/intermediate/tutorial11-normals/src/model.rs
- code/intermediate/tutorial12-camera/Cargo.toml
- code/intermediate/tutorial12-camera/src/model.rs
- code/intermediate/tutorial13-threading/Cargo.toml
- code/intermediate/tutorial13-threading/src/model.rs
- docs/beginner/tutorial9-models/README.md
Update code and relevant tutorial sections to work with tobj 3.0.
> Update tobj to 3.0.x

- docs/beginner/tutorial2-swapchain/README.md
- docs/beginner/tutorial3-pipeline/README.md
- docs/showcase/gifs/README.md
- docs/showcase/windowless/README.md
changed them in  beginner and showcase sections as well as changing attachment -> view.
BTW, thank you for this tutorial, it has been very helpful!
> Updated the use of RenderPassColorAttachmentDescriptor to RenderPassColorAttachment

- docs/intermediate/tutorial10-lighting/README.md
Fixes a couple of minor issues in the tutorial docs for tutorial 10 - Lighting, in the specular lighting section.
fixes #206
> fix: Tutorial 10 Docs Specular Lighting Shader Problems

- code/beginner/tutorial2-swapchain/src/challenge.rs
- code/beginner/tutorial2-swapchain/src/main.rs
- code/beginner/tutorial3-pipeline/src/challenge.rs
- code/beginner/tutorial3-pipeline/src/main.rs
- code/beginner/tutorial4-buffer/src/challenge.rs
- code/beginner/tutorial4-buffer/src/main.rs
- code/beginner/tutorial5-textures/src/challenge.rs
- code/beginner/tutorial5-textures/src/main.rs
- code/beginner/tutorial6-uniforms/src/challenge.rs
- code/beginner/tutorial6-uniforms/src/main.rs
- code/beginner/tutorial7-instancing/src/challenge.rs
- code/beginner/tutorial7-instancing/src/main.rs
- code/beginner/tutorial8-depth/src/challenge.rs
- code/beginner/tutorial8-depth/src/main.rs
- code/beginner/tutorial9-models/src/main.rs
- code/intermediate/tutorial10-lighting/src/main.rs
- code/intermediate/tutorial11-normals/src/main.rs
- code/intermediate/tutorial12-camera/src/main.rs
- code/intermediate/tutorial13-threading/src/main.rs
- code/showcase/compute/src/main.rs
- code/showcase/framework/src/lib.rs
- docs/beginner/tutorial2-swapchain/README.md
Fixing #200 by preventing resizing to 0 (wich I thinks is the problem)
I accidently put some pub fn istead of fn, but I'm to exausted to fix this now and it does not produce any errors (I edited 22 files by hand...)
> Fixing #200

- docs/beginner/tutorial3-pipeline/README.md
> Found a typo

- code/beginner/tutorial6-uniforms/src/shader.wgsl
- docs/beginner/tutorial6-uniforms/README.md
> fix type name Camera to CameraUniform

- code/beginner/tutorial9-models/src/model.rs
- code/intermediate/tutorial10-lighting/src/model.rs
- code/intermediate/tutorial11-normals/src/model.rs
- code/intermediate/tutorial12-camera/src/model.rs
- code/intermediate/tutorial13-threading/src/model.rs
- code/showcase/compute/src/model.rs
- code/showcase/framework/src/model.rs
- docs/beginner/tutorial9-models/README.md
- docs/intermediate/tutorial10-lighting/README.md
- docs/intermediate/tutorial11-normals/README.md
Adds the "_bind_group" suffix to the variables `camera` and `light` in model.rs (and where needed in .md files) to improve consistency.
> model.rs: added "_bind_group" where appropriate

- docs/beginner/tutorial2-surface/README.md
> Fix typo in tutorial2-surface README.md

- docs/intermediate/tutorial10-lighting/README.md
The `flags` member of `ShaderModuleDescriptor` was removed, `set_vertex_buffer` and `set_index_buffer` signatures weren't updated in `draw_mesh_instanced`, and a some cgmath->pod `.into`s were needed.
In addition, added some filename hints (especially for `light.wgsl`) since changes are across multiple different files.
> Update tutorial 10 to match types and remove deprecated flags

- docs/intermediate/tutorial12-camera/README.md
Add `SAFE_FRAC_PI_2` definition, conform to correct types, and make a newly-added line more clear.
> Minor update nits for tutorial 12

- code/beginner/tutorial3-pipeline/src/challenge.rs
Only one of the pipelines were actually adjusted, so let's fix that.
Side note: From what I can tell it doesn't seem like this example really works any more, but I'm not sure what's wrong with it. I think it starting but not working as expected is better than it crashing though.
> Fix challenge code for tutorial 3 crashing

- .gitignore
- docs/beginner/tutorial1-window/README.md
- docs/beginner/tutorial2-surface/README.md
- docs/beginner/tutorial3-pipeline/README.md
- docs/beginner/tutorial4-buffer/README.md
- docs/beginner/tutorial5-textures/README.md
I've been looking for a way to start learning graphics programming. This has helped a lot, thank you for writing the tutorials and maintaining them!
So far I've gone through the beginner tutorials 1 to 5 and fixed whatever I stumbled on.
> Some small fixes for beginner tutorials 1 to 5

- docs/beginner/tutorial2-surface/README.md
- docs/beginner/tutorial6-uniforms/README.md
- docs/intermediate/tutorial10-lighting/README.md
- docs/showcase/README.md
- docs/showcase/compute/README.md
- docs/showcase/gifs/README.md
Thank you for nice tutorials. I fixed some typos found while I was doing beginner tutorials. And I also fixed some typos found by [misspell](https://github.com/client9/misspell).
> Fix some typos

- docs/beginner/tutorial3-pipeline/README.md
> Update the description about WGSL

- docs/beginner/tutorial2-surface/README.md
Implementing state, etc is titled `//main.rs`, but the code should go in lib.rs.  Hopefully I'm not missing anything!
> Beginner - The Surface shows lib.rs but is labeled main.rs

- docs/beginner/tutorial1-window/README.md
Added a few small comments in brackets where explanations were potentially unclear. Also added the step of creating the crate.
> Clarified some of the steps in tutorial1-window

- docs/README.md
A large part of the Chinese version of this tutorial has already been completed. And the badge added here should be a quick link for anyone visiting the static site to easily visit this original repo.
> Add Chinese translation

- docs/beginner/tutorial5-textures/README.md
Found a broken link while following the tutorial
> Fixing broken link to pipeline section

- docs/beginner/tutorial2-surface/README.md
> Small text correction docs.

- docs/beginner/tutorial3-pipeline/README.md
- docs/showcase/windowless/README.md
> Fix `targets` data type in the doc

- docs/beginner/tutorial7-instancing/README.md
There's a syntax error in this wgsl code.
> Fix instance typo

- docs/beginner/tutorial6-uniforms/README.md
I think this was supposed to say "warp" as that makes more sense to me than wrap. I could be mistaken though.
> fixed typo

- code/beginner/tutorial2-surface/src/lib.rs
> Could'nt -> Couldn't

- docs/beginner/tutorial2-surface/README.md
The alternative code path missed the 0.13 update.
> Fix code example for 0.13

- docs/beginner/tutorial4-buffer/README.md
I think you can just state the formula which is most commonly used 
source: https://en.wikipedia.org/wiki/SRGB#Computing_the_transfer_function
> Correct color conversation between rgb and srgb in buffer tutorial

- docs/intermediate/tutorial12-camera/README.md
This pull request updates the "A Better Camera" chapter to fix an issue with the cameras pitch rotation.
Even though this patch was already implemented in the demo code with f46b2f6, the change was never reflected in the documentation.
> Updated incorrect camera pitch rotation

- docs/intermediate/tutorial10-lighting/README.md
- docs/intermediate/tutorial11-normals/README.md
Contains some minor fixes to the code included in the documentation for tutorials 10 and 11.
> Fixes to docs for tutorial 10 and tutorial 11

- docs/README.md
I closed [#415](https://github.com/sotrh/learn-wgpu/pull/415) and now simply added a new link.
> add a newly translated Chinese version link

- docs/beginner/tutorial8-depth/README.md
It adds more insights to what the field are for
> feat: added link to CompareFunction

- code/beginner/tutorial8-depth/src/challenge.rs
- code/beginner/tutorial8-depth/src/challenge.wgsl
- code/beginner/tutorial8-depth/src/texture.rs
Before modification (wrong depth map sampling)
After modification (correct depth map sampling)
> fix issue #442

- docs/beginner/tutorial2-surface/README.md
Fixed link which had a wrong path to local destination.
> fixed not working link

- docs/beginner/tutorial8-depth/README.md
> Add missing `view_formats`

- code/beginner/tutorial9-models/src/resources.rs
- docs/beginner/tutorial9-models/README.md
> fixed panic on loading obj without normals

- docs/beginner/tutorial2-surface/README.md
> fix a spell mistake at docs/beginner/tutorial2-surface/README.md

- docs/beginner/tutorial2-surface/README.md
- docs/intermediate/tutorial13-hdr/readme.md
Hi. Thank you for the awesome tutorials.
I found minor indent issues and this fixes them.
> Fix indentations

- docs/beginner/tutorial2-surface/README.md
> Fix typo in tutorial 2

- docs/intermediate/tutorial13-hdr/readme.md
Hi, it seems you got those two mixed up https://en.wikipedia.org/wiki/Geographic_coordinate_system#Latitude_and_longitude
> fix longitude/latitude explanation
