- docs/beginner/tutorial4-buffer/README.md
Keep `set_vertex_buffer` function to not mislead readers into replacing it instead of supplement it
> Remove misleading section

- code/beginner/tutorial6-uniforms/src/challenge.rs
- code/beginner/tutorial6-uniforms/src/main.rs
- code/beginner/tutorial7-instancing/examples/array_instances.rs
- code/beginner/tutorial7-instancing/examples/naive.rs
- code/beginner/tutorial7-instancing/examples/storage_instances.rs
- code/beginner/tutorial7-instancing/examples/texture_instances.rs
- code/beginner/tutorial7-instancing/examples/vertex_instances.rs
- code/beginner/tutorial7-instancing/src/challenge.rs
- code/beginner/tutorial7-instancing/src/main.rs
- code/beginner/tutorial8-depth/src/challenge.rs
- code/beginner/tutorial8-depth/src/main.rs
- code/beginner/tutorial9-models/src/main.rs
- code/intermediate/tutorial10-lighting/src/main.rs
- code/intermediate/tutorial11-normals/src/main.rs
- code/intermediate/tutorial12-camera/src/camera.rs
- code/research/camera/src/camera.rs
- code/research/performance/src/main.rs
- code/showcase/framework/src/camera.rs
- docs/beginner/tutorial5-textures/README.md
- docs/beginner/tutorial6-uniforms/README.md
- docs/beginner/tutorial7-instancing/README.md
- docs/intermediate/tutorial12-camera/README.md
Thanks for writing these! Having used opengl previously, I found the text clear and understandable.
Here are some minor tweaks:
* Remove mentions `&mut Queue` usage which no longer seem to be required.
* Fix a typo "now" -> "know".
* `#[cfg_attr(rustfmt, rustfmt_skip)]` -> `#[rustfmt::skip]`.
* `{ ...; return proj * view; }` -> `{ ...; proj * view }`
> Minor tweaks

- docs/showcase/windowless/README.md
It might be obvious to the ordinary users, but I I needed some time to figure out the difference, so I think it's nice to have some short comment about the TextureFormat for PNG. Does this make sense...?
> Add a comment about TextureFormat for PNG

- code/beginner/tutorial2-swapchain/src/challenge.rs
- code/beginner/tutorial2-swapchain/src/main.rs
- code/beginner/tutorial3-pipeline/src/challenge.rs
- code/beginner/tutorial3-pipeline/src/main.rs
- code/beginner/tutorial4-buffer/src/challenge.rs
- code/beginner/tutorial4-buffer/src/main.rs
- code/beginner/tutorial5-textures/src/challenge.rs
- code/beginner/tutorial5-textures/src/main.rs
- code/beginner/tutorial6-uniforms/src/challenge.rs
- code/beginner/tutorial6-uniforms/src/main.rs
- code/beginner/tutorial7-instancing/src/challenge.rs
- code/beginner/tutorial7-instancing/src/main.rs
- code/beginner/tutorial8-depth/src/challenge.rs
- code/beginner/tutorial8-depth/src/main.rs
- code/beginner/tutorial9-models/src/main.rs
- code/intermediate/tutorial10-lighting/src/main.rs
- code/intermediate/tutorial11-normals/src/main.rs
- code/intermediate/tutorial12-camera/src/main.rs
- code/showcase/gifs/src/main.rs
- code/showcase/pong/src/render/mod.rs
- docs/beginner/tutorial2-swapchain/README.md
- docs/showcase/gifs/README.md
`std::iter::once` is more idiomatic for passing single-value iterators than `Some(value)`, and it's even intended for this case
according to [the docs](https://doc.rust-lang.org/std/iter/fn.once.html).
> Use std::iter::once for encoder queue submission

- docs/beginner/tutorial2-swapchain/README.md
- docs/beginner/tutorial3-pipeline/README.md
- docs/beginner/tutorial9-models/README.md
- docs/news/README.md
Tutorial 2 - Swapchain
- Update `get_next_texture` to `get_current_frame`
- Fix typos
Tutorial 3 - Pipeline
- Add updated fields to `PipelineLayout` creation
Fix typos in News
> Fix typos and update Beginner tutorials 2, 3

- docs/beginner/tutorial1-window/README.md
- docs/beginner/tutorial2-swapchain/README.md
https://github.com/gfx-rs/wgpu-rs/commit/655828f88fee9d9f4a0985770fc012cc2fd6a7ec this commit renamed the `vulkan` feature which confused me when going through the initial setup.
> Update `vulkan` feature to `vulkan-portability` and fix small typo in swapchain

- docs/beginner/tutorial4-buffer/README.md
While working through the tutorials I had to update this using statement as DeviceExt is now in the wgpu::util namespace.
> DeviceExt is now in a util namespace

- docs/beginner/tutorial5-textures/README.md
Added parameter `&queue` to `texture::Texture::from_bytes` call.
> Add missing parameter on tutorial5 snippet

- code/intermediate/tutorial12-camera/Cargo.toml
- code/intermediate/tutorial12-camera/src/camera.rs
- code/intermediate/tutorial13-threading/Cargo.toml
- code/intermediate/tutorial13-threading/src/camera.rs
- code/showcase/framework/src/camera.rs
- docs/intermediate/tutorial12-camera/README.md
The new version of ```winit 0.23``` introduces breaking changes in API. They've changed field of the enum ```MouseScrollDelta::PixelDelta``` from ```LogicalPosition``` into ```PhysicalPosition```. I have only changed the files in which this problem occurs.
Also ```event_loop.primary_monitor()``` returns an ```Option``` now, but it appears in pong and decided not to touch it, because it's not related to the tutorial.
> Migration to winit 0.23

- docs/beginner/tutorial5-textures/README.md
I have broadly made three sets of changes:
1. General prose cleanup (eg. correcting minor syntax errors, rewriting some sentences to make them more clear)
2. Code consistency (eg. not making use of the `texture` wrapper until it is defined at the end of the page, not redefining the `size` variable, not declaring unused fields on `State`).
3. Adding necessary dependencies to `Cargo.toml`.
Please feel free to reject/challenge any of these changes as you see fit! I have tried to keep your (@sotrh) voice as consistent as possible, but if that's not the case, please just let me know.
> Cleanup Textures tutorial

- docs/beginner/tutorial3-pipeline/README.md
A link to The Cargo Book section on build scripts, to help those who want to learn more about them.
> Link to Cargo Book for more info about build scripts

- docs/beginner/tutorial4-buffer/README.md
Was missing the `slice` method
> Fix a typo in the code example

- docs/README.md
Hi, I think the learn-wgpu site has no link to this GitHub repository. I think it's easier for possible contributors to find the repo if there's a link around this section.
> Add a link to GitHub repo

- docs/beginner/tutorial8-depth/README.md
This is a leftover from the migration in #29
> Rename OUTPUT_ATTACHMENT to RENDER_ATTACHMENT in description

- docs/beginner/tutorial9-models/README.md
- docs/intermediate/tutorial10-lighting/README.md
- docs/intermediate/tutorial11-normals/README.md
- docs/intermediate/tutorial12-camera/README.md
- docs/intermediate/tutorial13-threading/README.md
Hey @sotrh! I just finished going through your tutorials and they're great! I have a few edits to suggest. Most of them were either code typos I found that were fixed in the `src` folders but not in the code snippets, and the rare text typo.
Feel free to ask me to revert any of these changes. They're pretty minor, I just figured other folks would appreciate the updates.
009: impl Vertex for ModelVertex was using the vertex_attr_array! macro.
009: RenderPipelineDescriptor has a `vertex` member not  `vertex_state`.
009: to_rgba() should be to_rgba8(), to_rgba is set to be deprecated.
010: BindGroupDescriptor has a `entries` member not `bindings`.
010: Remove re-declaration of mat4 model_matrix;
010: Prefer hard-coded [#.#; #] instead of `Foo::fn().into()`.
010: Clarify which shader …
> Misc typo and code fixes.

- Cargo.lock
- code/beginner/tutorial1-window/Cargo.toml
- code/beginner/tutorial2-swapchain/Cargo.toml
- code/beginner/tutorial3-pipeline/Cargo.toml
- code/beginner/tutorial4-buffer/Cargo.toml
- code/beginner/tutorial5-textures/Cargo.toml
- code/beginner/tutorial6-uniforms/Cargo.toml
- code/beginner/tutorial7-instancing/Cargo.toml
- code/beginner/tutorial8-depth/Cargo.toml
- code/beginner/tutorial9-models/Cargo.toml
- code/intermediate/tutorial10-lighting/Cargo.toml
- code/intermediate/tutorial11-normals/Cargo.toml
- code/intermediate/tutorial12-camera/Cargo.toml
- code/intermediate/tutorial13-threading/Cargo.toml
- code/showcase/compute/Cargo.toml
- code/showcase/compute/src/camera.rs
- code/showcase/gifs/Cargo.toml
- docs/beginner/tutorial1-window/README.md
- docs/beginner/tutorial3-pipeline/README.md
- docs/beginner/tutorial5-textures/README.md
- docs/intermediate/tutorial12-camera/README.md
Fix #160 
It seems there's no breaking change between winit 0.22 and 0.24 except for this one:
> Breaking: PixelDelta scroll events now return a PhysicalPosition.
(https://github.com/rust-windowing/winit/blob/master/CHANGELOG.md#0230-2020-10-02)
I think it's okay to use `PhysicalPosition` instead of `LogicalPosition`, but if the latter is preferred, I'll find how to convert them.
Also, this pull request updates wgpu to 0.7.1. This is because current Cargo.toml specifies:
``` toml
wgpu = "0.7"
```
so users who started the tutorial recently uses 0.7.1. It seems there's no visible difference, but I think it's good to match the actual version.
> Update winit to 0.24 and wgpu to 0.7.1

- docs/beginner/tutorial3-pipeline/README.md
- docs/beginner/tutorial5-textures/README.md
- docs/beginner/tutorial6-uniforms/README.md
Following the tutorial I found the `wgpu::ColorTargetState` struct construction was out of date, as the color and alpha components had been moved inside `BlendState`.
> wgpu 0.8 corrections

- docs/beginner/tutorial8-depth/README.md
clamp_depth no longer exists on DepthStencilState, and is instead only on PrimitiveState.
See: https://wgpu.rs/doc/wgpu/struct.DepthStencilState.html
> Remove clamp_depth from DepthStencilState

- docs/beginner/tutorial3-pipeline/README.md
The render pipeline page was missing the `clamp_depth` and `conservative` fields of the `wgpu::PrimitiveState` struct, added with wgpu 0.8.  These were correct in the full code, but not the snippets in the doc.
> Add missing fields in PrimitiveState

- docs/beginner/tutorial4-buffer/README.md
Note: I tried putting the lifetime to 'static but it didn't work. The solution was to put the result of the macro in a constant and then passing this constant to the `attributes` field
> Fix on vert_attr_array

- docs/beginner/tutorial2-surface/README.md
'instance' and 'adapter' are not defined (and not needed) in State.
> Fixed code snippet.

- docs/beginner/tutorial5-textures/README.md
As I was studying your tutorial, I noticed a code snipped not being ported over.
After testing the different enum options only the one with `aspect: wgpu::TextureAspect::All` will compile, so here is the change.
Thank you for your hard work creating the tutorial.
> Fixed issue with code example was not ported to 0.10.x

- docs/beginner/tutorial1-window/README.md
I helped someone resolve an issue on the rust game dev discord where they didnt realize the env_logger was important so left it out and then didnt realize why wgpu was giving such useless errors.
This change should help prevent people from making this mistake in the future.
Happy to completely rephrase the paragraph as needed.
> Add section on why env_logger is needed

- docs/beginner/tutorial5-textures/README.md
The code has been updated for wgpu-0.10 (`wgpu::TextureUsage::SAMPLED` -> `wgpu::TextureUsages::TEXTURE_BINDING`), but its comment was not updated at the same time.
Anyway, thanks for the great doc! It's really helpful for my first GPU programming.
> Update an explaining comment for its code

- docs/beginner/tutorial2-surface/README.md
As far as I can tell looking at the docs, there is no "first" method for the Iterator trait, but I believe "next" accomplishes getting the first item in this instance.
> No "first()" method on Iterator

- docs/showcase/windowless/README.md
TextureUsages::OUTPUT_ATTACHMENT doesn't exist. Changing to TextureUsages::RENDER_ATTACHMENT, which is what the code example uses.
> Typo: TextureUsages::OUTPUT_ATTACHMENT

- docs/intermediate/tutorial11-normals/README.md
Add `light_dir` and `view_dir`  to initial version of fragment shader, and rename use of `camera_uniform` to `camera` to match the uniform variable's name.
Additionally, improve the clarity of some examples so it's more clear what changed and where, and remove `.into()` (since these are already of the right types anyway).
> Add missing or rename shader vars

- docs/beginner/tutorial9-models/README.md
In tutorial 9, the model loading code populates `bind_group` which doesn't exist yet on `Material`.  Much later (after some screenshots to compare against), we are asked to add it.  Instead, add it from the beginning, and in the later section explain the need to use what's there.
While I'm here, fix the lifetime for `DrawModel`'s second implementation.
> Simplify the bind_group flow in tutorial 9

- docs/beginner/tutorial9-models/README.md
Since `desc` is part of the `Vertex` trait, the trait needs to be imported before it can be called.
> Explain why model::Vertex needs to be imported in tutorial 9

- docs/beginner/tutorial9-models/README.md
While easy to figure out what to do, it may be useful to explain why `rgba` was previously an `&ImageBuffer` already, and now is an `ImageBuffer` and later needs to be converted to a reference when passed to `write_texture` - `to_rgba8` created a new `ImageBuffer` for us.
> Provide explanation why rgba is no longer a reference

- docs/beginner/tutorial7-instancing/README.md
Following the instructions, build errors follow unless you import various cgmath traits (`Zero`, `Rotation3`, `InnerSpace`).  Since the code example uses the prelude import, add this prelude import to the tutorial.
> Add cgmath prelude import in tutorial 7

- code/beginner/tutorial8-depth/src/challenge.rs
The shader.wgsl contains entry point `vs_main` and `fs_main`, but the rust code would reference them `main` and `main`
It would cause the following crash when trying to run the code:
```
[2021-11-25T14:50:43Z ERROR wgpu::backend::direct] Handling wgpu errors as fatal by default
thread 'main' panicked at 'wgpu error: Validation Error
Caused by:
In Device::create_render_pipeline
note: label = `Render Pipeline`
error matching VERTEX shader requirements against the pipeline
unable to find entry point 'main'
```
> Fix depth buffer challenge

- docs/beginner/tutorial5-textures/README.md
The `VERTICES` listed in the tutorial were using the old Y values for `tex_coords` which made the texture appear upside down.
> Fixed flipped tex_coords in tutorial5-textures

- docs/README.md
- docs/beginner/tutorial2-surface/README.md
First thanks for putting this together. I really appreciate such resource about wgpu exists.
This PR contains some typo fixes to the main page. I'm not native speaker either but perhaps 2 non native speakers are better than one. I also have another ace up my sleeve since my GF is teaching English at university and was kind enough to proof read this. I will make few notes to the individual changes. Feel free to merge this or close the issue if you don't like the changes.
> Typo fixes in main README.md

- docs/beginner/tutorial2-surface/README.md
- docs/beginner/tutorial4-buffer/README.md
It seems there are a few more options in `Limit` and `Features`, so it might be nice to update these links (the other ones have little difference, but I included them for consistency).
> Update the links to wgpu's docs

- docs/beginner/tutorial3-pipeline/README.md
I guess it's your preference not to use such a shortcut for the sake of education, but I think `include_wgsl!` should be mentioned at least. `include_wgsl!` is already used in the code of the showcases.
> Mention include_wgsl!

- docs/showcase/compute/README.md
Fix to [Link to the "alignment" page is broken #291](https://github.com/sotrh/learn-wgpu/issues/291#issue-1092108325) issue.
In a rather counterintuitive way for me the link is broken, after a few random attempts this modification allows you to make it visitable.
> Fix to Link to the "alignment" page

- docs/beginner/tutorial5-textures/README.md
[`wgpu::BindingType::Sampler`](https://docs.rs/wgpu/latest/wgpu/enum.BindingType.html) now takes [`wgpu::SamplerBindingType`](https://docs.rs/wgpu/latest/wgpu/enum.SamplerBindingType.html) enum for specific type of a sampler binding. Sample code had already been corrected, but the document was not corrected yet.
> Fix `wgpu::SamplerBindingType` is now parameter of `wgpu::BindingType::Sampler`

- docs/beginner/tutorial4-buffer/README.md
`rasterization_state` is an old field name of `wgpu::RenderPipelineDescriptor` (I could find it in wgpu v0.4.0). This PR fixes it to `primitive`.
> Fix old field name

- code/beginner/tutorial8-depth/src/challenge.rs
- docs/beginner/tutorial7-instancing/README.md
`NUM_INSTANCES` is defined in a guide and a code, but it is never used so I removed it in this PR.
> Remove unused constant `NUM_INSTANCES`

- code/beginner/tutorial6-uniforms/src/challenge.rs
- code/beginner/tutorial6-uniforms/src/main.rs
- code/beginner/tutorial7-instancing/src/challenge.rs
- code/beginner/tutorial7-instancing/src/main.rs
- code/beginner/tutorial8-depth/src/challenge.rs
- code/beginner/tutorial8-depth/src/main.rs
- code/beginner/tutorial9-models/src/main.rs
- code/intermediate/tutorial10-lighting/src/main.rs
- code/intermediate/tutorial11-normals/src/main.rs
- docs/beginner/tutorial6-uniforms/README.md
Fix #300 
These variables are stored but never used in actual. As you commented on #300, it might be great if there's also these controls, but these are not what we cannot live without. Considering the purpose of the tutorials, probably it's a good idea to remove them to avoid confusion, at least for now.
> Remove is_{up,down}_pressed

- code/beginner/tutorial4-buffer/src/challenge.rs
- code/beginner/tutorial4-buffer/src/main.rs
- code/beginner/tutorial5-textures/src/challenge.rs
- code/beginner/tutorial5-textures/src/main.rs
- code/beginner/tutorial6-uniforms/src/challenge.rs
- code/beginner/tutorial6-uniforms/src/main.rs
- code/beginner/tutorial7-instancing/src/challenge.rs
- code/beginner/tutorial7-instancing/src/main.rs
- code/beginner/tutorial8-depth/src/challenge.rs
- code/beginner/tutorial8-depth/src/main.rs
- docs/beginner/tutorial4-buffer/README.md
I *think* these paddings are no longer needed because `create_buffer_init()` now ensures the alignment.
c.f. https://github.com/gfx-rs/wgpu/blob/01f62baad2811c1cd6aa254608dfee000c316b46/wgpu/src/util/device.rs#L53-L60
> Remove a padding in INDICES

- docs/beginner/tutorial4-buffer/README.md
I found [a tip](https://github.com/gfx-rs/wgpu/discussions/1790#discussioncomment-1160378) to use `vertex_attr_array!` with a function. If you like this, I'd like to mention this. If not, please just ignore :)
``` rs
impl Vertex {
const ATTRIBS: [wgpu::VertexAttribute; 2] =
wgpu::vertex_attr_array![0 => Float32x3, 1 => Float32x3];
fn desc<'a>() -> wgpu::VertexBufferLayout<'a> {
use std::mem;
wgpu::VertexBufferLayout {
array_stride: mem::size_of::<Self>() as wgpu::BufferAddress,
step_mode: wgpu::VertexStepMode::Vertex,
attributes: &Self::ATTRIBS,
}
}
}
```
> Add one more advice about vertex_attr_array! macro

- docs/beginner/tutorial2-surface/README.md
`frame.view` does not exist in the whole tutorial and is probably a remant
from older versions. The text is actually referring to `view`
> docs: surface: change frame.view to view

- docs/beginner/tutorial6-uniforms/README.md
This PR removes a note about the `[[block]]` decorator which is no longer needed (as mentioned in [the news page section](https://github.com/sotrh/learn-wgpu/blob/4d0be61d76d156db8c8f1a6a2b97ea70b5506ec8/docs/news/0.12/readme.md?plain=1#L12) added by 7a42a0d4db1fa17121d5f7b285d5e6ca865b65a2).
I was very confused for some time trying to figure out what this sentence was referring to, and I think it can be removed, since it is no longer in the WGSL spec.
> tut6: remove sentence about block decorator

- docs/intermediate/tutorial13-threading/README.md
Correcting typo in the docs/tutorial13-threading.
Propably -> Probably
> Fix a minor typo in docs/tutorial13-threading

- docs/intermediate/tutorial11-normals/README.md
`wgpu::BindingType::Sampler` is a tuple like variant in wgpu 0.12
> Correct an error in the normal map tutorial

- docs/intermediate/tutorial11-normals/README.md
The shader panics (see below) because `half_dir` is missing so I added it.
```
❯ cargo run
Compiling graphic_rust v0.1.0 (/home/rokonio/dev/rust/graphic_rust)
Finished dev [unoptimized + debuginfo] target(s) in 5.39s
Running `target/debug/graphic_rust`
[2022-02-20T10:27:50Z ERROR wgpu::backend::direct] Handling wgpu errors as fatal by default
thread 'main' panicked at 'wgpu error: Validation Error
Caused by:
In Device::create_shader_module
note: label = `Shader`
Shader 'Shader' parsing error: no definition in scope for identifier: 'half_dir'
┌─ wgsl:93:57
│
93 │     let specular_strength = pow(max(dot(tangent_normal, half_dir), 0.0), 32.0);
│                                                         ^^^^^^^^ unknown identifier
no definition in scope for identifier: 'half_dir'
', …
```
> Add missing half_dir

- docs/intermediate/tutorial10-lighting/README.md
Noticed those while following the tutorial, didn't do a thorough check though, so there could be others.
> Fix typos in Working with Lights: The normal matrix

- docs/beginner/tutorial9-models/README.md
This PR is required to use `tobj::load_model_buf_async`.
https://github.com/Twinklebear/tobj/releases/tag/3.2.0
> fix tobj version

- code/beginner/tutorial9-models/src/resources.rs
- code/intermediate/tutorial10-lighting/src/resources.rs
- code/intermediate/tutorial11-normals/src/resources.rs
- code/intermediate/tutorial12-camera/src/resources.rs
- docs/beginner/tutorial9-models/README.md
Removes some unnecessary indentation, visible in the 'Model Loading' chapter but also appearing in other code files.  There's some other minor formatting adjustments from `rustfmt`, but these are nearly negligible.
> Fix indentation

- Cargo.lock
When I run `cargo run --bin tutorial1-window`, I get the following error. It seems the commit the current `Cargo.lock` refers to no longer exists. This pull request just reflect the change by `cargo update -p https://github.com/gfx-rs/wgpu#0.12.0`. Note that I don't run all of the examples, so some more tweaks might be needed.
```
Updating git repository `https://github.com/gfx-rs/wgpu`
error: failed to get `wgpu` as a dependency of package `tutorial10-lighting v0.1.0 (C:\Users\Yutani\Documents\GitHub\learn-wgpu\code\intermediate\tutorial10-lighting)`
Caused by:
failed to load source for dependency `wgpu`
Caused by:
Unable to update https://github.com/gfx-rs/wgpu?branch=gecko#f99d8604
Caused by:
object not found - no match for id (f99d8604039549272abf523abc0a2cc2d4ac4fb9); class=Odb (9); …
```
> Update Cargo.lock for wgpu gecko branch

- docs/beginner/tutorial2-surface/README.md
Minor error, at starting of [The Surface](https://sotrh.github.io/learn-wgpu/beginner/tutorial2-surface/#first-some-housekeeping-state), the code snippets points to `main.rs` while its code actually belongs to `libs.rs`.
> fix: point code snippet to right file name

- docs/beginner/tutorial1-window/README.md
It seems that in #345 pollster was removed from the example, but not from the code in the page.
This change removes it from the code in the tutorial, so it will work just by pasting it in the editor.
> Removed "pollster" from tutorial1-window readme.

- docs/beginner/tutorial5-textures/README.md
This line used to say `diffuse_image.as_rgba8().unwrap();`, which got changed to `diffuse_image.to_rgba8().unwrap();` in b8b84440303c486d76d252977cea5d8b8e771aef.
Because `to_rgba()` does not return an `Option` like `as_rgba()`, the `.unwrap()` causes an error.
> Remove incorrect .unwrap()

- docs/beginner/tutorial9-models/README.md
This causes an error when constructing the struct from `load_model` in resources.rs.
The fields are already `pub` in the code, but not in the docs:
https://github.com/sotrh/learn-wgpu/blob/bcb4282f1ef9e70fa88a518905c532625c38b255/code/beginner/tutorial9-models/src/model.rs#L11-L15
> Fixed missing `pub` in ModelVertex struct

- docs/beginner/tutorial5-textures/README.md
> fix: typo in write_texture

- docs/intermediate/tutorial10-lighting/README.md
- docs/intermediate/tutorial11-normals/README.md
- docs/intermediate/tutorial12-camera/README.md
The beginner tutorials sets everything up in `lib.rs` rather than `main.rs`. This is just a little change to bring the intermediate tutorials in line with what the beginner tutorials set up.
> Replace main.rs with lib.rs in intermediate tutorials

- docs/beginner/tutorial2-surface/README.md
get_preferred_format no longer exists as per https://docs.rs/wgpu/0.13.1/wgpu/struct.Surface.html#method.get_supported_formats
> Use 0.13's Surface::get_supported_formats

- docs/beginner/tutorial1-window/README.md
Needed this to get things rendering for me! otherwise we get:
```
$ cargo run
Compiling rustp v0.1.0 (/Users/jack/dev/rustp)
warning: unused implementer of `Future` that must be used
--> src/main.rs:4:5
|
4 |     run();
|     ^^^^^^
|
= note: `#[warn(unused_must_use)]` on by default
= note: futures do nothing unless you `.await` or poll them
warning: `rustp` (bin "rustp") generated 1 warning
Finished dev [unoptimized + debuginfo] target(s) in 0.48s
Running `target/debug/rustp`
```
> Fix some code for Dependencies and the window

- docs/beginner/tutorial5-textures/README.md
The texture coordinates used by the `Sampler` are inherently uncorrelated to the framebuffer coordinates corresponding to the `Fragment`. Although the `Sampler` is used in `Fragment`, the sampler can be sampled in any fragment using any texture coordinates, such as Gaussian blur.
The description in the [WebGPU Spec](https://gpuweb.github.io/gpuweb/#dictdef-gpusamplerdescriptor) is more accurate and easier to understand:
`magFilter`
> Specifies the sampling behavior when the sample footprint is smaller than or equal to one texel.
`minFilter`
> Specifies the sampling behavior when the sample footprint is larger than one texel. This often comes into play when viewing a surface from up close, or from far away.
`nearest`
> Return the value of the texel nearest to the texture coordinates. …
> Fix the descriptions of `mag_filter` and `min_filter` fields

- docs/beginner/tutorial4-buffer/README.md
The definition of `step_mode` on WebGPU Spec is easier to understand, and it's not "seems redundant in our case".
[GPUVertexStepMode](https://gpuweb.github.io/gpuweb/#enumdef-gpuvertexstepmode) ：
> The step mode configures how an address for vertex buffer data is computed, based on the current vertex or instance index
[GPUVertexBufferLayout's stepMode field](https://gpuweb.github.io/gpuweb/#dom-gpuvertexbufferlayout-stepmode)
> Whether each element of this array represents per-vertex data or per-instance data
> Make `step_mode` easier to understand

- docs/beginner/tutorial5-textures/README.md
The image shows a pentagon, not a hexagon.
> changed hexagon to pentagon

- docs/beginner/tutorial1-window/README.md
The sample HTML file given for the beginner window tutorial does not include an element with the id `wasm-example` as required by:
```rust
use winit::platform::web::WindowExtWebSys;
web_sys::window()
.and_then(|win| win.document())
.and_then(|doc| {
let dst = doc.get_element_by_id("wasm-example")?;
...
```
in the `lib.rs` file.
> Fix: Could not append canvas error when running on wasm

- docs/intermediate/tutorial11-normals/README.md
Some anomalies I encountered in the Normal Mapping section's code blocks. In particular, the plumbing of a command buffer through Texture::from_image(..)'s return type.
> Fix to docs for tutorial 11

- code/beginner/tutorial8-depth/src/texture.rs
- code/beginner/tutorial9-models/src/texture.rs
- code/intermediate/tutorial10-lighting/src/texture.rs
- code/intermediate/tutorial11-normals/src/texture.rs
- code/intermediate/tutorial12-camera/src/texture.rs
- code/intermediate/tutorial13-terrain/src/texture.rs
- code/showcase/compute/src/texture.rs
- code/showcase/framework/src/texture.rs
- code/showcase/mouse-picking/src/texture.rs
- code/showcase/threading/src/texture.rs
- docs/beginner/tutorial8-depth/README.md
Negative values like `-100.0` are illegal for `GPUSamplerDescriptor.lodMinClamp`.
More specifically, WebGPU valid usage states that `lodMinClamp` must not be negative, and `lodMaxClamp` must be >= `lodMinClamp`:
> descriptor.[lodMinClamp](https://gpuweb.github.io/gpuweb/#dom-gpusamplerdescriptor-lodminclamp) ≥ 0.
> descriptor.[lodMaxClamp](https://gpuweb.github.io/gpuweb/#dom-gpusamplerdescriptor-lodmaxclamp) ≥ descriptor.[lodMinClamp](https://gpuweb.github.io/gpuweb/#dom-gpusamplerdescriptor-lodminclamp).
Indeed, Chrome's WebGPU implementation complains:
```console
LOD clamp bounds [-100.000000, 100.000000] contain contain a negative number.
- While validating [SamplerDescriptor]
- While calling [Device].CreateSampler([SamplerDescriptor]).
```
It dislikes it even more when we actually …
> Stop using illegal negative values for `wgpu::SamplerDescriptor::lod_min_clamp`.

- docs/beginner/tutorial2-surface/README.md
The explanation for the `format` field of the `SurfaceConfiguration` struct currently references outdated information about the `get_preferred_format` method, which has been removed from WGPU. This PR replaces that section of the explanation with up-to-date information about the replacement `get_supported_formats` method.
> fix: update outdated info on getting supported formats.

- docs/beginner/tutorial8-depth/README.md
There was no instruction on the field to add to State.
It can be easily found, but it's better if in the tutorial
> fix: Missing struct field

- docs/beginner/tutorial9-models/README.md
When following the [rendering a mesh](https://sotrh.github.io/learn-wgpu/beginner/tutorial9-models/#rendering-a-mesh) part, I was kind of lost, so I added a little more info
Edit: I actually had to look at the code to be sure of what I was doing
> feat: added more information on obj_model setup

- docs/beginner/tutorial2-surface/README.md
There is an & reference on the window parameter in one of the example code snippets which seems to be there by mistake. This PR removes it.
> Removing & reference from new() parameter

- docs/beginner/tutorial7-instancing/README.md
I find it clearer if the comment explaining why 4 slots are needed is moved before the first slot definition.
> Improve instancing `VertexBufferLayout` creation comments order

- docs/beginner/tutorial2-surface/README.md
There is this point in the tutorial where we have just implemented `State::resize`, but then the example code shows a call to `State::input` which has not yet been implemented and won't be until the next section
> Remove erroneous code from future

- docs/beginner/tutorial1-window/README.md
Most of the changes are removing and adding commas, capitalizing all words like 'Cargo' and 'JavaScript' and adding articles before some words where needed. All in all, these are changes to enhance the reading experience.
If you aprove of these changes, I would do the same for the other *tutorial readmes*.
> Small changes to enhance the reading experience for the Tutorial1

- docs/beginner/tutorial2-surface/README.md
WGPU 0.18 made the `occlusion_query_set` and `timestamp_writes` fields mandatory in `RenderPassColorAttachment`. This was fixed in the code for the tutorials but not in the actual tutorial. This PR fixes that.
> Added missing fields to RenderPassDescriptor

- docs/beginner/tutorial1-window/README.md
- docs/beginner/tutorial2-surface/README.md
- docs/beginner/tutorial3-pipeline/README.md
- docs/beginner/tutorial4-buffer/README.md
- docs/beginner/tutorial5-textures/README.md
- docs/beginner/tutorial6-uniforms/README.md
- docs/beginner/tutorial7-instancing/README.md
- docs/beginner/tutorial8-depth/README.md
- docs/beginner/tutorial9-models/README.md
- docs/intermediate/tutorial10-lighting/README.md
- docs/intermediate/tutorial11-normals/README.md
- docs/intermediate/tutorial12-camera/README.md
- docs/intermediate/tutorial13-hdr/readme.md
- docs/intermediate/wip-terrain/README.md
As promised, I have made a handful of changes in the Beginner and Intermediate sections. The changes are: fixed typos, added/removed commas where needed, broke down some sentences for clarity, added articles before some words where needed, capitalized some words like (GPU, CPU, Rust, Cargo), changed the order of wording in some sentences for clarity, some italic and bold effects were inconsistent so I made them consistent. All in all, these are changes to enhance the reading experience.
If you approve of these changes, I will do the same for the News, Showcase, and Introduction sections.
> Improvements for Beginner and Intermediate sections

- docs/beginner/tutorial2-surface/README.md
Came across this as I was following the tutorial. It seems like this line is no longer correct for the current version of `wgpu`.
Hope this is helpful, and thanks for this excellent resource on wgpu!
> Correct outdated line of example code in surface tutorial

- docs/beginner/tutorial2-surface/README.md
I found two instances where the text did not perfectly reflect what the code was doing. I double checked that the code in the README.md matches the code in the folder and since it was matching, I adjusted the text.
> Fix inconsistencies between code and text

- docs/beginner/tutorial2-surface/README.md
Fixes two typos in the surface tutorial chapter.
> Fix typos in surface tutorial

- docs/beginner/tutorial2-surface/README.md
ScaleFactorChanged doesn't have the same signature. The default implementation as of `winit "0.29"` automatically resizes the window and triggers a Resized event on ScaleFactorChanged.
See https://docs.rs/winit/latest/winit/event/enum.WindowEvent.html#variant.ScaleFactorChanged
MainEventsCleared has been replaced with AboutToWait.
https://github.com/rust-windowing/winit/pull/2976
> Remove ScaleFactorChanged. MainEventsCleared no longer exists.

- docs/beginner/tutorial2-surface/README.md
While the actual code is right, the tutorial was missing the `memory_hints` field - added a line mentioning what they are as well.
This is a great tutorial, thank you for writing it!
> fix: Add reference to `memory_hints`

- docs/beginner/tutorial2-surface/README.md
The DeviceDescriptor creation for wgpu 22.0 is missing a field.
This was correctly set in the code but not in the Markdown doc.
(thank you for this awesome tutorial !)
> fix DeviceDescriptor creation

- docs/beginner/tutorial2-surface/README.md
This comment is inaccurate. Drop order doesn't matter in this case, because this struct only holds a reference. Dropping it does nothing, the surface has its own reference to the window.
The actual window is owned by the scope outside of `State` and thus references to it that are kept in the `State` are valid.
The lifetime of the `Surface` takes care of not allowing for dropping the window while the surface exists.
I also removed a stray space at the end of a line.
> Remove an inaccurate comment.

- docs/beginner/tutorial2-surface/README.md
- docs/beginner/tutorial3-pipeline/README.md
- docs/beginner/tutorial4-buffer/README.md
- docs/beginner/tutorial5-textures/README.md
The window field was introduced in tutorial 1 but was not mentioned in the subsequent tutorials. As I'm still a beginner, please feel free to correct me if I've misunderstood anything.
> fix missing field `window`

- docs/beginner/tutorial4-buffer/README.md
It describes how the index buffer needs to be ordered counterclockwise for `FrontFace::CCw` and clockwise for `FrontFace::Cw`.
> Added a Note about the Index buffer

- code/beginner/tutorial6-uniforms/src/challenge.rs
- code/beginner/tutorial6-uniforms/src/lib.rs
- code/beginner/tutorial7-instancing/src/challenge.rs
- code/beginner/tutorial8-depth/src/challenge.rs
- code/beginner/tutorial8-depth/src/lib.rs
- code/beginner/tutorial9-models/src/lib.rs
- code/intermediate/tutorial10-lighting/src/lib.rs
- code/intermediate/tutorial11-normals/src/lib.rs
- code/intermediate/tutorial12-camera/src/camera.rs
- code/intermediate/wip-terrain/src/camera.rs
- code/showcase/compute/src/camera.rs
- code/showcase/framework/src/camera.rs
- code/showcase/mouse-picking/src/camera.rs
- code/showcase/threading/src/camera.rs
- docs/beginner/tutorial6-uniforms/README.md
- docs/intermediate/tutorial12-camera/README.md
Fixes https://github.com/sotrh/learn-wgpu/issues/517.
This has also been discussed in https://github.com/sotrh/learn-wgpu/issues/478.
There is discussion about whether to switch to `glam` instead of `cgmath` to fix this issue and get rid of  `OPENGL_TO_WGPU_MATRIX` entirely, but fixing the tutorial _quickly_ to not cause further confusion to beginners has a much higher priority compared to that, in my opinion, especially because this is essentially the first Google result for WGPU beginners.
> Fix `OPENGL_TO_WGPU_MATRIX`

- docs/beginner/tutorial5-textures/README.md
The position suggested to insert new code in the doc doesn't exit in the demo, I replace it so learners can better locate where to add new code.
> Fix Typo in Tutorial5 Textures

- code/beginner/tutorial2-surface/src/lib.rs
- docs/beginner/tutorial2-surface/README.md
The docs mention
> We'll also call update() before it, too
but this call seems to be missing. This PR fixes that 😄
> Fix missing call to `update()` in tutorial 2

- docs/beginner/tutorial1-window/README.md
Shadowing `state` during decomposition of WindowEvent is slightly confusing.
Also, it is more similar to tutorial 2.
> In tutorial 1, use key_state instead of shadowed state - as similar to tutorial 2
